<table id="example" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Username</th>
                <th>Permission</th>
                <th>Name</th>
                <th>Email</th>
                <th>Mobile</th>
                <th>Address</th>
                <th></th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>Username</th>
                <th>Permission</th>
                <th>Name</th>
                <th>Email</th>
                <th>Mobile</th>
                <th>Address</th>
                <th></th>
            </tr>
        </tfoot>
    </table>